version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
    container_name: premium-calc-api
    ports:
      - "${API_PORT:-3000}:3000"
    volumes:
      - ./api/data:/usr/src/app/data
      - ./data_files:/usr/src/app/data_files
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
    container_name: premium-calc-frontend
    ports:
      - "${FRONTEND_PORT:-80}:80"
    environment:
      - API_URL=http://api:3000
    depends_on:
      - api
    restart: unless-stopped